{
 "title": "Water-Distribution-Network-Overview",
 "time": { "from": "2017-05-14T17:20:52.966Z", "to": "2017-05-20T12:23:59.957Z" },
 "panels": [
  { "title": "Pipeline2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "pipeline2 - Flow Prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"flow_prediction\")"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"flow\")"
    }
   ]
  },
  { "title": "Pipeline1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r.node != \"1\" and r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "pipeline1: Random Forest Clf for Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"leak_detection\")"
    }
   ]
  },
  { "title": "Pipeline0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r.node != \"1\" and r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "pipeline0 - FSM Correlation for Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"fsm_corr\" and r.node != \"1\")"
    }
   ]
  },
  { "title": "General Network Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r.node != \"1\" and r._field == \"pressure\")"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"flow\")"
    }
   ]
  },
  { "title": "Examples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Node 2: Normalized pressure and FSM Correlation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"pressure\" and r.node == \"21\")\n    |> map(fn: (r) => ({r with _value: r._value / 70.0}))"
    },
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"fsm_corr\" and r.node == \"21\")"
    }
   ]
  },
  {
   "title": "pipeline2 - Flow Prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"flow_prediction\" and r.link == \"21\")"
    },
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2017-01-01T00:00:00Z, stop: 2017-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"flow\" and r.link == \"21\")"
    }
   ]
  }
 ]
}