{
 "title": "Metrics",
 "time": { "from": "2022-08-03T22:10:42.807Z", "to": "2022-08-03T22:26:15.415Z" },
 "panels": [
  {
   "title": "Metrics: pipeline0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"metric_value\" and r._measurement == \"pipeline0\")"
    }
   ]
  },
  {
   "title": "Metrics: pipeline1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"metric_value\" and r._measurement == \"pipeline1\")"
    }
   ]
  },
  {
   "title": "Metrics: pipeline2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"metric_value\" and r._measurement == \"pipeline2\")"
    }
   ]
  },
  {
   "title": "Metrics: pipeline3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket:\"primary\")\n    |> range(start: 2022-01-01T00:00:00Z, stop: 2022-12-31T12:00:00Z)\n    |> filter(fn: (r) => r._field == \"metric_value\" and r._measurement == \"pipeline3\")"
    }
   ]
  }
 ]
}